const tasks = [
    {
        id: 1,
        text: 'Visit a local coffee (or boba) shop',
        icon: 'fa-solid fa-mug-saucer ',
        description: "Make small talk with the barista! Mention you're new to Redwood City and ask if they have recommendations.",
        complete: false,
    },
    {
        id: 2,
        text: 'Hang out with friends at Stanford',
        icon: 'fa-solid fa-tree ',
        description: 'I think you said you knew a couple people there?',
        complete: false,
    },
    {
        id: 3,
        text: 'Go to a dance class',
        icon: 'fa-solid fa-radio ',
        description: 'Dance Vita and Motion Arts Center have lots of social classes that seem beginner-friendly.',
        complete: false,
    },
    {
        id: 4,
        text: "Go to Alekz's housewarming party",
        icon: 'fa-solid fa-cake-candles ',
        description: 'Oct 14!',
        complete: false,
    },
    {
        id: 5,
        text: 'Volunteer at an animal shelter',
        icon: 'fa-solid fa-paw ',
        description: "Pets in Need opens fall volunteer recruitment in October! If it's too hard to volunteer, just visit the shelter and chat with whoever's working there.",
        complete: false,
    },
    {
        id: 6,
        text: 'Go to a a concert',
        icon: 'fa-solid fa-music ',
        description: "Alone or with someone else -- doesn't really matter",
        complete: false,
    },
    {
        id: 7,
        text: 'Ask other new grads at work to hang out',
        icon: 'fa-solid fa-message ',
        description: 'You could send a message to the Slack channel asking if anyone wants to do somethign after work?',
        complete: false,
    },
    {
        id: 8,
        text: 'Talk to someone at the Snowflake gym',
        icon: 'fa-solid fa-dumbbell ',
        description: 'Or any gym -- just chat with someone.',
        complete: false,
    },
    {
        id: 9,
        text: 'Join an intermural sports league',
        icon: 'fa-solid fa-volleyball ',
        description: "It doesn't even have to be a real sport. Do kickball or something.",
        complete: false,
    },
    {
        id: 10,
        text: 'Go to a pool hall and meet people',
        icon: 'fa-solid fa-compact-disc',
        description: "Looks like there's a Wednesday night pool group in San Mateo. (also there were no free pool icons)",
        complete: false,
    },
    {
        id: 11,
        text: 'Join a dating app',
        icon: 'fa-solid fa-heart ',
        description: 'i know i know but picture this: it could be fun?',
        complete: false,
    },
    {
        id: 12,
        text: 'Attend a mixer at a brewery',
        icon: 'fa-solid fa-beer-mug-empty ',
        description: 'not going to deal with the html for links but here: https://www.meetup.com/bay-area-outdoor-coffee-meetup/events/296141026/',
        complete: false,
    },
    {
        id: 13,
        text: "Ask to join someone's cafeteria table",
        icon: 'fa-solid fa-burger',
        description: 'And then talk to them ofc',
        complete: false,
    },
    {
        id: 14,
        text: 'Cook a meal with someone',
        icon: 'fa-solid fa-kitchen-set ',
        description: 'anyone',
        complete: false,
    },
    {
        id: 15,
        text: "Get an acquaintance's phone number",
        icon: 'fa-solid fa-mobile-screen-button ',
        description: 'and then text then and ask them if they want to hang out',
        complete: false,
    },
    {
        id: 16,
        text: "Call a friend you haven't spoken to recently",
        icon: 'fa-solid fa-phone ',
        description: 'Could be someone from Brown or something',
        complete: false,
    },
    {
        id: 17,
        text: 'Get a table for one at a restaurant',
        icon: 'fa-solid fa-chair ',
        description: '(!)',
        complete: false,
    },
    {
        id: 18,
        text: 'Go on a hike',
        icon: 'fa-solid fa-mountain-sun ',
        description: 'Or an urban walk. Ideally invite someone to join you. There are lots of hiking meetup groups too.',
        complete: false,
    },
    {
        id: 19,
        text: 'Say hi to a dog and talk to the owner',
        icon: 'fa-solid fa-dog ',
        description: 'more small talk (or big talk idk whatever floats your boat)',
        complete: false,
    },
    {
        id: 20,
        text: 'Go to a Brown alumni group event',
        icon: 'fa-solid fa-graduation-cap ',
        description: 'copied and pasted links 4 u: http://www.brownsv.club/events, https://brownclubgsf.com/events, https://www.facebook.com/groups/svbrownalums/',
        complete: false,
    },
    {
        id: 21,
        text: 'Go out to dinner with a new friend',
        icon: 'fa-solid fa-utensils ',
        description: "Like someone you didn't know before coming to the Bay Area",
        complete: false,
    },
    {
        id: 22,
        text: 'Attend a work social event',
        icon: 'fa-solid fa-users ',
        description: 'Surely they have these',
        complete: false,
    },
    {
        id: 13,
        text: 'Go to a board game meetup',
        icon: 'fa-solid fa-chess ',
        description: "another link i don't want to properly deal with: https://www.meetup.com/fremont-board-games-meetup-group/events/295892370/",
        complete: false,
    },
    {
        id: 24,
        text: 'Plan a trip to see friends',
        icon: 'fa-solid fa-plane ',
        description: "You should come visit Seattle! Corey will be here over winter break. It's also super cheap (<$100 round trip sometimes).",
        complete: false,
    },
    {
        id: 25,
        text: 'Meet someone at a club',
        icon: 'fa-solid fa-martini-glass ',
        description: 'You can totally go alone, just be safe about it obviously',
        complete: false,
    },
];

export default tasks;
