const tasks = [
    {
        id: 1,
        text: 'Visit a local cafe',
        icon: 'fa-solid fa-utensils ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 2,
        text: 'Attend a community event',
        icon: 'fa-solid fa-music ',
        description: 'Participate in a local community event or gathering.',
        complete: false,
    },
    {
        id: 3,
        text: 'Take a city tour',
        icon: 'fa-solid fa-palette ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 4,
        text: 'Join a language exchange',
        icon: 'fa-solid fa-earth-africa ',
        description: 'Participate in a local community event or gathering.',
        complete: false,
    },
    {
        id: 5,
        text: 'Visit a museum',
        icon: 'fa-solid fa-landmark ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 6,
        text: 'Visit a local cafe',
        icon: 'fa-solid fa-utensils ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 7,
        text: 'Attend a community event',
        icon: 'fa-solid fa-music ',
        description: 'Participate in a local community event or gathering.',
        complete: false,
    },
    {
        id: 8,
        text: 'Take a city tour',
        icon: 'fa-solid fa-palette ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 9,
        text: 'Join a language exchange',
        icon: 'fa-solid fa-earth-africa ',
        description: 'Participate in a local community event or gathering.',
        complete: false,
    },
    {
        id: 10,
        text: 'Visit a museum',
        icon: 'fa-solid fa-landmark ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 11,
        text: 'Visit a local cafe',
        icon: 'fa-solid fa-utensils ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 12,
        text: 'Attend a community event',
        icon: 'fa-solid fa-music ',
        description: 'Participate in a local community event or gathering.',
        complete: false,
    },
    {
        id: 13,
        text: 'Take a city tour',
        icon: 'fa-solid fa-palette ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 14,
        text: 'Join a language exchange',
        icon: 'fa-solid fa-earth-africa ',
        description: 'Participate in a local community event or gathering.',
        complete: false,
    },
    {
        id: 15,
        text: 'Visit a museum',
        icon: 'fa-solid fa-landmark ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 16,
        text: 'Visit a local cafe',
        icon: 'fa-solid fa-utensils ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 17,
        text: 'Attend a community event',
        icon: 'fa-solid fa-music ',
        description: 'Participate in a local community event or gathering.',
        complete: false,
    },
    {
        id: 18,
        text: 'Take a city tour',
        icon: 'fa-solid fa-palette ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 19,
        text: 'Join a language exchange',
        icon: 'fa-solid fa-earth-africa ',
        description: 'Participate in a local community event or gathering.',
        complete: false,
    },
    {
        id: 20,
        text: 'Visit a museum',
        icon: 'fa-solid fa-landmark ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 21,
        text: 'Visit a local cafe',
        icon: 'fa-solid fa-utensils ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 22,
        text: 'Attend a community event',
        icon: 'fa-solid fa-music ',
        description: 'Participate in a local community event or gathering.',
        complete: false,
    },
    {
        id: 23,
        text: 'Take a city tour',
        icon: 'fa-solid fa-palette ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
    {
        id: 24,
        text: 'Join a language exchange',
        icon: 'fa-solid fa-earth-africa ',
        description: 'Participate in a local community event or gathering.',
        complete: false,
    },
    {
        id: 25,
        text: 'Visit a museum',
        icon: 'fa-solid fa-landmark ',
        description: 'Enjoy a cup of coffee or tea at a nearby cafe.',
        complete: false,
    },
];

export default tasks;
